# Generated by Django 5.0.14 on 2026-06-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_event_subscriptions'),
        ('saas', '0003_encrypt_user_name_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_d99c0d_idx',
            old_name='notif_recip_tenant_status_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='saas.tenant'),
        ),
    ]
