# Generated by Django 5.0.14 on 2026-06-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_entity__c2633a_idx',
            old_name='audit_log_entity_type_entity_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_tenant__ed9ce1_idx',
            old_name='audit_log_tenant_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_actor_i_2ba9f4_idx',
            old_name='audit_log_actor_id_created_at_idx',
        ),
    ]
