# Generated by Django 5.0.14 on 2026-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit",
            "0002_rename_audit_log_entity_type_entity_id_idx_audit_log_entity__c2633a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("status_change", "Status Change"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("disbursed", "Disbursed"),
                    ("repaid", "Repaid"),
                    ("defaulted", "Defaulted"),
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("role_assigned", "Role Assigned"),
                    ("role_removed", "Role Removed"),
                    ("subscribed", "Subscribed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
