# Generated by Django 5.0.14 on 2026-06-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('saas', '0003_encrypt_user_name_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentrecord',
            name='billing_pay_gateway_ref_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_tenant_status_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='saas.tenant'),
        ),
    ]
