# Generated by Django 5.0.14 on 2026-06-26 21:03

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_plan_planfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
